### ISSUE TITLE
Obfuscated code?

### ISSUE THREAD

**Issue by jowsey** [yukifuyuki/fc-catgirls#1]
Hi! Just came across this and it seems pretty cool, but just curious why you've obfuscated all the code? Doesn't seem in the spirit of open source to do so, unless this was unintentional?

This makes it really hard to check what the code's doing, which I would prefer to be able to do just out of principle, and makes it basically impossible to diff :(

**Comment by yukifuyuki** [comment]
I have the source code in a separate private repository, and kinda "build" these from it. I don't really intend for this to be open-source per se (although with front-end web stuff there's not much choice in the matter >.<)

As for what the code is doing... outside of changing the HTML UI, it cleans up the user input (FC URL or ID), then makes a bunch of fetch calls to xivapi.com for the data and displays it. First, it fetches the FC data to get a list of the FC member IDs, then makes fetch calls on each of those characters individually and stores the data and displays it in a nice format. The API has a request rate limit of 1 per second, which is why the calls have 1.1 seconds delay in between.
